#!/usr/bin/env bash

echo 'handling overwrites and setup for config...'

if [ -z "$1" ]; then
  echo "supply ssh keyname in comma-seperated format, like 'key,key2'"
  exit 1
fi
IFS=',' read -ra SSH_KEY_NAMES <<< "$1"

SSH_DIR="$HOME/.ssh"
if [ ! -d $SSH_DIR ]; then
    echo "setting up .ssh dir..."
    mkdir -m 700 $SSH_DIR
    echo "ssh dir created!"

    echo "creating ssh config file (you need to add the config!)"
    touch $SSH_DIR/config
    chmod 600 $SSH_DIR/config
    echo "config file created!"

    echo "creating keys (you still need to add the keys!)..."
    for key in "${SSH_KEY_NAMES[@]}"; do
        touch $SSH_DIR/{$key,$key.pub}
        chmod 600 $SSH_DIR/{$key,$key.pub}
    done
    echo "key files created!"
fi

echo "setting XDG user dirs (rename if needed and re-run)..."
xdg-user-dirs-update
echo "dirs updated!"

echo "installing applications and sdks..."
mkdir -p $NVM_DIR && \
PROFILE=/dev/null curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.5/install.sh | bash && \
source ~/.bashrc && \
nvm install --lts && \
npm install -g pnpm
echo "installed!"

echo "script completed!"
