# https://github.com/danyspin97/wpaperd?tab=readme-ov-file
[default]
#duration = "30m"
mode = "stretch"
path = "~/pictures/backgrounds/earth-sunrise-6016x3889-12523.jpg"

[any]
[DP-2]
[DP-3]
path = "~/pictures/backgrounds/earth-sunrise-6016x3889-12523.jpg"
